- name: Set-up and Start MongoDB Database
  hosts: mongodb_hosts
  become: true
  tasks:
    - name: Import MongoDB public key
      apt_key: 
        keyserver: hkp://keyserver.ubuntu.com
        id: 7F0CEB10
        state: present

    - name: Add MongoDB Repository
      apt_repository: 
        repo: 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen'
        state: present

    - name: Install MongoDB
      package:
        name: mongodb-org
        state: present
        update_cache: yes

    - name: Start MongoDB
      service:
        name: mongodb
        state: started
        
    - name: Create MongoDB user
      mongodb_user:
        login_port: '27017'
        database: "{{ db_name }}"
        login_user: "{{ db_user }}"
        login_password: "{{ db_pass }}"
        name: "{{ db_user }}"
        password: "{{ db_pass }}"
        roles: "root"
