- name: Build and Upload underwriter Artifact
  hosts: temp 
  tasks:
    - name: Ensure wget Present
      package:
        name: wget
        status: present
    - name: Ensure Suitable Directory exists
      file:
        path: /tmp/alinems/underwriter
        state: directory
    - name: Checkout Underwriter Code from Github
      git:
        repo: https://github.com/Cloud-Sharks/aline-underwriter-microservice-my.git
        dest: /tmp/alinems/underwriter
        singe_branch: yes
        version: master
    - name: Init and Update Submodule
      command:
        cmd: git submodule init && git submodule update
        chdir: /tmp/alinems/underwriter/aline-underwriter-microservice-my
    - name: Generate Underwriter Artifact
      command: 
        cmd: mvn package -DskipTests
        chdir: /tmp/alinems/underwriter/aline-underwriter-microservice-my
    - name: Start Underwriter Artifact
      shell:
        cmd: nohup java -jar underwriter-microservice-0.1.0.jar &
        chdir: /tmp/alinems/underwriter/aline-underwriter-microservice-my/underwriter-microservice/target
