- name: Build and Upload user Artifact
  hosts: temp 
  tasks:
    - name: Ensure Suitable Directory exists
      file:
        path: /tmp/alinems/user
        state: directory
    - name: Checkout User Code from Github
      git:
        repo: https://github.com/Cloud-Sharks/aline-user-microservice-my.git
        dest: /tmp/alinems/user
        version: master
    - name: Init and Update Submodule
      shell:
        cmd: git submodule init && git submodule update
        chdir: /tmp/alinems/user/
    - name: Generate User Artifact
      shell: 
        cmd: mvn package -DskipTests
        chdir: /tmp/alinems/user/
    - name: Start User Artifact
      shell:
        cmd: nohup java -jar user-microservice-0.1.0.jar &
        chdir: /tmp/alinems/user/user-microservice/target
